name: Deploy Application Code

on:
  push:
    branches:
      - main
    # This now triggers on changes to either Lambda code or the Spark script
    paths:
      - "src/**"
      - "spark_scripts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539772768:role/github-actions-deployer-role
          aws-region: us-east-1

      - name: Deploy process-trip-start Lambda
        run: |
          cd src/process_trip_start
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name process-trip-start --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy process-trip-end Lambda
        run: |
          cd src/process_trip_end
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name process-trip-end --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy trigger-aggregation Lambda
        run: |
          cd src/trigger_aggregation
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name trigger-aggregation --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy redrive-trip-end-events Lambda
        run: |
          cd src/redrive_trip_end_events
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name redrive-trip-end-events --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy emr-job-trigger Lambda
        run: |
          cd src/emr_job_trigger
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name emr-job-trigger --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy Spark Script to S3
        run: |
          aws s3 cp spark_scripts/emr_kpi_aggregator.py s3://bolt-ride-kpis/scripts/emr_kpi_aggregator.py
