name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539772768:role/github-actions-deployer-role
          aws-region: us-east-1

      - name: Deploy process-trip-start
        run: |
          cd src/process_trip_start
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name process-trip-start --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy process-trip-end
        run: |
          cd src/process_trip_end
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name process-trip-end --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy trigger-aggregation
        run: |
          cd src/trigger_aggregation
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name trigger-aggregation --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy redrive-trip-end-events
        run: |
          cd src/redrive_trip_end_events
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name redrive-trip-end-events --zip-file fileb://deployment_package.zip
          rm deployment_package.zip

      - name: Deploy emr-job-trigger
        run: |
          cd src/emr_job_trigger
          zip -r ../../deployment_package.zip .
          cd ../../
          aws lambda update-function-code --function-name emr-job-trigger --zip-file fileb://deployment_package.zip
          rm deployment_package.zip
